# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 00:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='nome')),
                ('data_nascimento', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(blank=True, default=None, max_length=15, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(blank=True, default=None, max_length=255, verbose_name='Telefone')),
                ('whatsapp', models.CharField(blank=True, default=None, max_length=255, verbose_name='Whatsapp')),
                ('email', models.EmailField(blank=True, default=None, max_length=255, verbose_name='E-mail')),
                ('data_conversao', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de Conversão')),
                ('data_batismo', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Data de Batismo')),
                ('cep', models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Cep')),
                ('cidade', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Cidade')),
                ('endereco', models.CharField(blank=True, default=None, max_length=255, verbose_name='Endereço')),
                ('bairro', models.CharField(blank=True, default=None, max_length=255, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=255, verbose_name='Complemento')),
                ('ponto_de_referencia', models.CharField(blank=True, default=None, max_length=255, verbose_name='Ponto de Referência')),
                ('foto', models.FileField(blank=True, default=None, null=True, upload_to='imagens/foto')),
                ('estado_civil', models.CharField(blank=True, choices=[('Solteiro', 'Solteiro'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado')], default='', max_length=100, verbose_name='Estado Civil')),
            ],
        ),
    ]
