# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 00:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_batismo',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data de Batismo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_conversao',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data de Conversão'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Data de Nascimento'),
        ),
    ]
