# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-28 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20180228_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='cpf',
            field=models.CharField(blank=True, default=None, max_length=15, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
