# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-10 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20180407_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_batismo',
            field=models.DateField(blank=True, verbose_name='Data de Batismo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_conversao',
            field=models.DateField(blank=True, verbose_name='Data de Conversão'),
        ),
    ]
