# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-23 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20180423_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_batismo',
            field=models.DateField(null=True, verbose_name='Data de Batismo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_conversao',
            field=models.DateField(null=True, verbose_name='Data de Conversão'),
        ),
    ]
