# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-26 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0010_auto_20180423_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='foto',
            field=models.FileField(default=None, upload_to='imagens/foto'),
        ),
    ]
