# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-27 19:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0013_auto_20180426_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='data_batismo',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Data de Batismo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_conversao',
            field=models.DateField(default=datetime.date.today, null=True, verbose_name='Data de Conversão'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='data_nascimento',
            field=models.DateField(blank=True, default=datetime.date.today, verbose_name='Data de Nascimento'),
        ),
    ]
