# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-07 14:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20180228_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='ponto_de_referencia',
        ),
        migrations.RemoveField(
            model_name='registro',
            name='whatsapp',
        ),
    ]
